version: "3.7"
services:
  db-localize-api:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name: db-localize-api
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3317:3306
    environment:
      MYSQL_DATABASE: localize_api
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - .docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - localize-api

  backend-localize-api:
    depends_on:
      - db-localize-api
    build:
      args:
        user: localize_api
        uid: 1000
      dockerfile: Dockerfile
    image: backend-localize-api
    container_name: backend-localize-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
      - 8017:8000
    networks:
      - localize-api

networks:
  localize-api:
    driver: bridge
